### PR TITLE
VQE demo using qiskit-alt

### PR DESCRIPTION
**Pull request by saharbenrached**
I created this demo with a random Pauli operator. It would be however interesting to work on an example of a molecule

### CODE REVIEW

**Comment by garrison** [comment]
This is cool!  [Here's the preview.](https://github.com/saharbenrached/qiskit-alt/blob/vqe-demo/demos/qiskit_alt_vqe_demo.ipynb)

A few files got added that don't belong in the repo and should be removed.  I made a PR in #29 that adjusts `.gitignore` so that these files would not have been added.

**Comment by saharbenrached** [comment]
Given a Pauli operator, I want to convert it to a sum of Pauli gates using QuantumOps from qiskit-alt. Which method to use?

**Comment by saharbenrached** [comment]
This is the demo for VQE for the H2 molecule, however, the result is incorrect. I am working on it

**Comment by jlapeyre** [comment]
I missed that you have actually deleted those files!
Thanks.

**Pull request merged**
